### ISSUE TITLE
The package name of the glibc statically linked should include the glibc version number

### ISSUE THREAD

**Issue by songdongsheng** [stunnel/static-curl#102]
if your static linking program use libdl and the GNU C Library version in the build system is newer than the version in the target system, you may get the following error:

```
$ podman run --rm -it registry.suse.com/suse/sle15:15.3
$ podman run --rm -it registry.suse.com/suse/sle15:15.4
$ podman run --rm -it registry.suse.com/suse/sle15:15.5

# zypper in -y xz tar; 

# curl -sSL https://github.com/stunnel/static-curl/releases/download/8.11.0/curl-linux-x86_64-glibc-8.11.0.tar.xz | tar -xvJf-
curl
trurl

# ./curl
curl: dl-call-libc-early-init.c:37: _dl_call_libc_early_init: Assertion `sym != NULL' failed.
Aborted (core dumped)
```

Thus the package file name with glibc, e.g. `curl-linux-x86_64-glibc-8.11.0.tar.xz` should named with `curl-linux-x86_64-gnu.2.36-8.11.0.tar.xz` use Zig target triple name.

**Comment by songdongsheng** [comment]
I don't recommend statically linking glibc, because it has very poor support for static linking. It's better to **dynamically link glibc** and **statically link other third-party libraries**.

**Comment by travislee89** [comment]
> I don't recommend statically linking glibc, because it has very poor support for static linking. It's better to **dynamically link glibc** and **statically link other third-party libraries**.

Yes, but this will not work on distros that lack glibc or have a low version of glibc.  
The aim of this project is to create a distro-agnostic binary.

In the next release, the dev package will switch to the musl library instead glibc, and it is recommended to use the musl version.
