### ISSUE TITLE
[Feature Request] Any plan on macOS?

### ISSUE THREAD

**Issue by NekoLSD** [stunnel/static-curl#14]

**Comment by travislee8964** [comment]
I have checked cURL on macOS, including the system's built-in version and the one installed through Homebrew, and none of them have nghttp3 compiled.
I will look at it, but I've never compiled a C program on macOS before.

**Comment by travislee8964** [comment]
All are excellent compilers, compiling cURL and related components, are pretty much the same.
The script in this repository uses clang for native architectures and gcc for cross-compilation.

**Comment by travislee8964** [comment]
It's done, it only supports x86_64 for now, I'll see how to cross-compile it to arm64.

**Comment by travislee8964** [comment]
It supports arm64 now.
