### ISSUE TITLE
Include Public Suffix List to avoid global cookies

### ISSUE THREAD

**Issue by jgraichen** [stunnel/static-curl#51]
Would it be possible to build the static curl with `libpsl` to support the public suffix list for cookies, and to avoid global super cookies?

**Comment by travislee89** [comment]
I will take a look at it.

**Comment by travislee89** [comment]
I raised a [PR](https://github.com/stunnel/static-curl/pull/52) and [compiled it](https://github.com/stunnel/static-curl/actions/runs/7491983747) so you can download it from Actions Artifacts and test if it works.

**Comment by jgraichen** [comment]
Awesome! Quick test looks good so far, but `curl -V` mentions `libpsl/0.21.2 (no IDNA support)` despite `curl` itself using `libidn2/2.3.2`.

**Comment by travislee89** [comment]
curl's configure script always checks for the libpsl with builtin, if build libpsl with libidn2 or libicu, it cann't be found.
`checking for library containing psl_builtin... -lpsl`
