### ISSUE TITLE
How to build libcurl.so ?

### ISSUE THREAD

**Issue by lux5am** [stunnel/static-curl#71]
Added --enable-shared still didn't produce libcurl.so
I need it for python/lua binding for openwrt arm64.

**Comment by travislee89** [comment]
Try removing `--enable-static --disable-shared` and build it.

**Comment by travislee89** [comment]
Try removing `--enable-ares`,
You may need to remove other static compilation parameters.

**Comment by lux5am** [comment]
Okay thanks I figured out.
