### ISSUE TITLE
curl 8.7.1: --dns-ipv6-addr and --dns-ipv4-addr options

### ISSUE THREAD

**Issue by nfn** [stunnel/static-curl#72]
Hi

Using curl 7.76.1 from Alma Linux 9.4 I'm able to set the IPv4 and IPv6 DNS, but with curl 8.7.1 from this repo, it shows the following results:

`curl --dns-ipv4-addr 1.1.1.1 --dns-ipv6-addr 2606:4700:4700::1111 --compressed -k -m 10 -X GET https://example.com`
`curl: (6) Could not resolve host: example.com`

Thanks

**Comment by travislee89** [comment]
I have reproduced it here as well.
The results are still different on different servers, some resolve DNS properly using only `--dns-ipv4-addr`, some need to use `--dns-ipv6-addr`.
But using `--dns-servers` are all fine.

```
curl --dns-servers 1.1.1.1 \
--compressed -m 10 \
-v -s -o /dev/null \
-X GET https://example.com
```

I'll check what `--dns-ipv4-addr` and `--dns-ipv6-addr` are about

**Comment by nfn** [comment]
Hi

My example is not good since I used CF dns servers, but --dns-ipv4-addr and --dns-ipv6-addr binds the request to a specific ip address.

Thanks

**Comment by travislee89** [comment]
Yeah, I checked the docs and it says that `--dns-ipv4-addr` and `--dns-ipv6-addr` are used to bind the local ip addresses.

You can check whether these commands were executed correctly.
```
ping -c 4 -I [local IPv4 address] [your dns server IPv4]
ping -c 4 -I [local IPv6 address] [your dns server IPv6]

dig -b [local IPv4 address] @[your dns server IPv4] example.com
dig -b [local IPv6 address] @[your dns server IPv6] example.com
```

**Comment by sergeevabc** [comment]
``` console
$ ver && echo; && curl --version

Microsoft Windows [Version 6.1.7601]

curl 8.13.0 (x86_64-w64-mingw32) libcurl/8.13.0 OpenSSL/3.4.1 brotli/1.1.0 zstd/1.5.7 c-ares/1.34.4 libidn2/2.3.8 libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.65.0 nghttp3/1.8.0
Release-Date: 2025-04-02
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile NTLM PSL SSL SSLS-EXPORT threadsafe TLS-SRP TrackMemory UnixSockets zstd

$ curl --dns-servers 204.12.237.197:5353 --head bible4u.lib
curl: (6) Could not resolve host: bible4u.lib
```

However, it should be resolved.

``` console
$ dig bible4u.lib @204.12.237.197 -p 5353 +short
157.230.194.58

$ doggo bible4u.lib @204.12.237.197:5353 --short
157.230.194.58

$ q bible4u.lib @204.12.237.197:5353 --short
157.230.194.58
```

It feels like Curl is not processing the custom port.
