### ISSUE TITLE
Add support for boringssl

### ISSUE THREAD

**Issue by perklet** [stunnel/static-curl#73]

**Comment by travislee89** [comment]
I'll take a look a few days later, but it won't release a binary with boringssl, you can fork it and then set your parameters to compile it.

**Comment by travislee89** [comment]
Sorry, I've tested this many times and boringssl is too much trouble to integrate with libssh, nghttp3, nghttp2 and other libraries.  
So this requirement will not be handled for now.

**Comment by perklet** [comment]
OK, thanks for you effort.
