### ISSUE TITLE
often encounter the following issue on aarch64

### ISSUE THREAD

**Issue by super-vip** [stunnel/static-curl#80]
./curl --version
curl: dl-call-libc-early-init.c:37: _dl_call_libc_early_init: assumption `sym != NULL’ failed.
Aborted (core dumped)

**Comment by super-vip** [comment]
[root@k8s-kuboard v8-3.2-20240630]# uname
Linux

[root@k8s-kuboard v8-3.2-20240630]# arch
aarch64

[root@k8s-kuboard v8-3.2-20240630]# cat /etc/os-release 
PRETTY_NAME="UnionTech OS Server 20"
NAME="UnionTech OS Server 20"
VERSION_ID="20"
VERSION="20"
ID="uos"
PLATFORM_ID="platform:uel20"
HOME_URL="https://www.chinauos.com/"
BUG_REPORT_URL="https://bbs.chinauos.com/"
VERSION_CODENAME="fuyu"

root@k8s-kuboard v8-3.2-20240630]# ldd --version
ldd (GNU libc) 2.28
......

@travislee89 This is not just the case on this aarch64 host, but you may encounter the previously mentioned errors on aarch64 hosts with different hardware platforms as well.

**Comment by travislee89** [comment]
Please use `musl` version on UnionTech OS Server

**Comment by super-vip** [comment]
OK. The Musl-based version is fine.
